### Run example code
< {%
    request.variables.set("input", [
        {
            "templateId": "php83",
            "args": "--name \"Elon Mask\" -age=45",
            "files": {
                "index.php": "<?php\n// /index.php\n\n// Some comment\n require_once __DIR__ . '/src/foo.php';\nrequire_once __DIR__ . '/src/bar/bar.php';\n\n// Call functions\n$resultFoo = foo();\nsleep(0);\n$resultBar = bar();\n\n// Calculate\n$product = $resultFoo * $resultBar;\n\n// Result\nvar_dump($product);\nvar_dump('Second output');",
                "src/foo.php": "<?php\n\nfunction foo() {\n    return 20;\n}",
                "src/bar/bar.php": "<?php\n\nfunction bar() {\n    return 3;\n}"
            }
        },
        {
            "templateId": "golang_1_23",
            "args": "--name \"Elon Mask\" -age=45",
            "files": {
                "main.go": "// You can edit this code!\n// Click here and start typing.\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"Hello, 世界\")\n}",
                "go.mod": "module play\n"
            }
        },
        {
            "templateId": "python_3",
            "args": "--name \"Elon Mask\" -age=45",
            "files": {
                "main.py": "import requests\n\ndef fetch_example():\n    response = requests.get(\"https://jsonplaceholder.typicode.com/todos/1\")\n    if response.status_code == 200:\n        print(\"Данные:\", response.json())\n    else:\n        print(\"Ошибка:\", response.status_code)\n\nif __name__ == \"__main__\":\n    fetch_example()\n",
                "requirements.txt": "requests==2.31.0\n"
            }
        }
    ])
%}

POST https://codenire.com/run
Content-Type: application/json

{
  "templateId": "{{$.input..templateId}}",
  "args": {{$.input.args}},
  "files": {{$.input..files}}
}
