### Run example code

< {%
    request.variables.set("clients", [
        {"templateId": "php83"}
    ])
%}

POST https://codenire.com/run
Content-Type: application/json

{
  "templateId": "{{$.clients..templateId}}",

  "args": "--name \"Elon Mask\" -age=45",

  "files": {
    "index.php": "<?php\n// /index.php\n\n// Some comment\n require_once __DIR__ . '/src/foo.php';\nrequire_once __DIR__ . '/src/bar/bar.php';\n\n// Call functions\n$resultFoo = foo();\n$resultBar = bar();\n\n// Calculate\n$product = $resultFoo * $resultBar;\n\n// Result\nvar_dump($product);",
    "src/foo.php": "<?php\n\nfunction foo() {\n    return 20;\n}",
    "src/bar/bar.php": "<?php\n\nfunction bar() {\n    return 3;\n}"
  }
}

### PRIVATE API (ONLY LOCAL)

### Runned Docker Images
POST https://codenire.com/images/list
Content-Type: application/json



### Register new Docker Image
POST https://codenire.com/images/register
Content-Type: application/json

{
  "name":  "PHP 8.3",
  "alias": "php83",
  "files":  {
    "Dockerfile": "FROM php:8.3-cli-alpine\n\nCOPY --from=composer:2 /usr/bin/composer /usr/bin/composer\n\nWORKDIR /app\n"
  },
  "runCmd": ""
}



### Run example go code

< {%
    request.variables.set("clients", [ // test data
        {"templateId": "go"}
    ])
%}

POST https://codenire.com/run
Content-Type: application/json

{
   "templateId": "{{$.clients..templateId}}",
   "args": "--name \"Elon Mask\" -age=45",
   "files": {
    "main.go": "package main\n\nimport (\n\t\"fmt\"\n)\n\nfunc main() \n\tfmt.Println(\"Hello, World!\")\n}\n"
  }
}