
### Run example code
POST http://127.0.0.1:8081/run
Content-Type: application/json

{
  "templateId": "php83",

  "args": "--name \"Elon Mask\" -age=45",

  "files": {
    "index.php": "<?php\n// /index.php\n\n// Подключаем файлы с функциями\n require_once __DIR__ . '/src/foo.php';\nrequire_once __DIR__ . '/src/bar/bar.php';\n\n// Вызываем функции\n$resultFoo = foo();\n$resultBar = bar();\n\n// Вычисляем произведение\n$product = $resultFoo * $resultBar;\n\n// Выводим результат\nvar_dump($product);",
    "src/foo.php": "<?php\n\nfunction foo() {\n    return 20;\n}",
    "src/bar/bar.php": "<?php\n\nfunction bar() {\n    return 3;\n}"
  }
}


### Runned Docker Images
POST http://127.0.0.1:8080/images/list
Content-Type: application/json


### Register new Docker Image
POST http://127.0.0.1:8080/images/register
Content-Type: application/json

{
  "name":  "PHP 8.3",
  "alias": "php83",
  "files":  {
    "Dockerfile": "FROM php:8.3-cli-alpine\n\nCOPY --from=composer:2 /usr/bin/composer /usr/bin/composer\n\nWORKDIR /app\n"
  },
  "runCmd": ""
}


###


POST http://127.0.0.1:8080/images/list
