### Golang 1.23
POST {{url}}/run
Content-Type: application/json

{
  "templateId": "default",
  "actionId": "ruby3.3",
  "files": {
    "script.rb": "puts \"Hello, World!\""
  },
  "args": "--name Mark",
  "stdin": "100.00"
}
