#!/bin/sh

# We use >&2 to write debugging output to stderr. tusd
# will forward these to its stderr. Any output from the
# hook on stdout will be captured by tusd and interpreted
# as a response.

isGolang="$(cat /dev/stdin | jq -e '.Event.Request.templateId == "foo"')"

if [ "$isGolang" = "true" ]; then
  cat <<END
  {
    "HTTPResponse": {
      "StatusCode": 400,
      "Body": "Golang not supported",
      "Headers": [],
      "Prevent": true
    }
  }
END

  exit 0
fi