### Bash 5.2
POST {{url}}/run
Content-Type: application/json

{
  "templateId": "bash",
  "files": {
    "script.sh": "#!/bin/bash\n\necho \"PGDATABASE is: $PGDATABASE\"\n"
  },
  "args": "--name Mark",
  "stdin": "100.00"
}

### Bash version
POST {{url}}/run
Content-Type: application/json

{
  "templateId": "bash",
  "actionId": "default",
  "files": {},
  "args": "--name Mark",
  "stdin": "100.00",
  "externalOptions": {
    "CompileCmd": "bash --version"
  }
}
