### Golang 1.23
POST {{url}}/run
Content-Type: application/json

{
  "templateId": "golang_1_23",
  "files": {
    "main.go": "// You can edit this code!\n// Click here and start typing.\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"Hello, 世界\")\n}"
  },
  "args": "--name Mark",
  "stdin": "100.00"
}
