### Golang 1.23
POST {{url}}/run
Content-Type: application/json

{
  "templateId": "bash",
  "files": {
    "script.sh": "#!/bin/bash\n\necho \"PGDATABASE is: $PGDATABASE\"\n"
  },
  "externalOptions": {
  },
  "args": "--name Mark",
  "stdin": "100.00"
}
