openapi: 3.0.0
info:
  title: Submission API
  version: "1.0.0"
  description: API for managing code submissions

paths:
  /run:
    post:
      summary: Run Sandbox
      operationId: runSandbox
      requestBody:
        description: Run a sandbox
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SandboxRequest'
      responses:
        "200":
          description: Submission ran successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SandboxResponse'
  /images/list:
    get:
      summary: Get image config list
      operationId: getImageConfigList
      responses:
        "200":
          description: Get list templates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageConfigList'

components:
  schemas:
    SandboxResponse:
      type: object
      properties:
        error:
          type: string
        exitCode:
          type: integer
        stdout:
          type: string
          format: byte
        stderr:
          type: string
          format: byte
      required:
        - exitCode
        - stdout
        - stderr

    SandboxRequest:
      type: object
      properties:
        sandId:
          type: string
        binary:
          type: string
          description: files in tar archive encoded with base64
        args:
          type: string
        extendedOptions:
          type: object
          additionalProperties:
            type: string
      required:
        - sandId
        - binary
        - args

    ImageConfigOption:
      type: object
      properties:
        CompileTTL:
          type: integer
        RunTTL:
          type: integer
        MemoryLimit:
          type: integer
      required:
        - SourceFile

    ImageConfigScriptOptions:
      type: object
      properties:
        SourceFile:
          type: string
      required:
        - SourceFile

    ImageConfig:
      type: object
      properties:
        Template:
          type: string
        Name:
          type: string
        Groups:
          type: array
          items:
            type: string
        Version:
          type: string
        CompileCmd:
          type: string
        RunCmd:
          type: string
        Workdir:
          type: string
        Options:
          $ref: '#/components/schemas/ImageConfigOption'
        ScriptOptions:
          $ref: '#/components/schemas/ImageConfigScriptOptions'
        DefaultFiles:
          type: object
          additionalProperties:
            type: string
        Provider:
          description: Configuration provider (built-in, api, external)
          type: string
      required:
        - Template
        - Id
        - Name
        - Groups
        - CompileCmd
        - RunCmd
        - Options
        - ScriptOptions
        - DefaultFiles
        - Version
        - Workdir
        - Provider

    ImageConfigList:
      type: array
      items:
        $ref: '#/components/schemas/ImageConfig'